language: go
go: 1.8.x

matrix:
  fast_finish: true
  include:
    - os: linux
      sudo: required
      addons:
        apt:
          packages:
            - libusb
            - libusb-dev
    - os: osx
      sudo: false
      osx_image: xcode8.3
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
      before_install:
        - brew install libusb

env:
  global:
    - CGO_ENABLED=1

script:
  - GOARCH=386 go build -o "bin/antgo-${TRAVIS_OS_NAME}-x86" -i .
  - GOARCH=amd64 go build -o "bin/antgo-${TRAVIS_OS_NAME}-x64" -i .

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: GYnaLQtdN5foT7XHzwnw7QHdO1+lYEG0SZ2C7CNhSkUISwMMbGJV/7NPw93SHbEvseeAAYKaAcQEM+o9B9DqpGx+VqqB7COLPCkKhDTakjWiKnFHZTsT1mWD6l4hsHSp/TGLBAn0xPolz9nPgw1IGOpWfx2WIopSZfLYSi/sJK8TjJvKagdv3OGw8xwcfo5ojW+3HcjOEn13jw2BZ844QQope96+qsuwNQEyWLlWwFXnEpSLGPhRATuKCibfxsPUNjU1ccDrga51VrJTwAxeXbPC//KPEAvH5I7PcmvhGywYGRFSa6lr3nfq8/MjiMvkZFs8q0CjiR/I/gFfecjx/DY3g0/6D7lpC6ShyMdLW+VOd2VxkSETpFbHC7Da7H2ZcdcBOFkiZVEf9/7jNsMltrc5+CILnrgvVJAHE5GD67pdWmhXHZhvtSNDcsItw0c8EC37KyVJ9N7E6sq19uSRBCacgMGXuh0f3iKcHM/8xUb660G/XpRqOcoCTDdxBrVclPXMCANRkpQ4xzaACe8T46LuT90xmEsIirH5yTH0mrVx0vQ82zDc0KwMI0+ApnjaiVegrI1RNmw/ieWe4wsG5oaN1cywoQh5COhJ1hcgw0wGJs+569ILF5FLN8NXBULKOXcrYQGPSY3Qh+dx2z1ByQg9sVg8cJY7sUgaAjSaTRM=
  file_glob: true
  file: bin/*
  on:
    branch: master
    repo: half2me/antgo
    tags: false

notifications:
  email: false
