platform: x64

clone_folder: c:\msys64\go\src\github.com\half2me\antgo

install:
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw64/mingw-w64-x86_64-go mingw64/mingw-w64-x86_64-libusb && pkg-config --list-all && export GOROOT=/mingw64/lib/go && export GOPATH=/go && export CGO_ENABLED=1 && go get github.com/half2me/antgo/... && go build -o antgo-win64.exe -i github.com/half2me/antgo"

artifacts:
  - path: C:\msys64\home\appveyor\antgo-win64.exe
    name: binary

#deploy:
#  release: antgo-win-$(appveyor_build_version)
#  description: 'Antgo'
#  provider: GitHub
#  auth_token:
#    secure: Aj+IX99Zm3sC+GBkE0eJxMV6k7jubTkpAkBYTgxjZNh5qgsmDAmLHZYadBq0a952
#  artifact: binary # This is the name we specified in the artifacts section.
#  draft: true
#  prerelease: true
#  on:
#    branch: master