platform: x64

clone_folder: c:\gopath\src\github.com\half2me\antgo

environment:
  GOPATH: c:\gopath

install:
  - choco install pkgconfiglite
  - appveyor DownloadFile http://github.com/libusb/libusb/releases/download/v1.0.21/libusb-1.0.21.7z
  - 7z x -y libusb-1.0.21.7z
  - xcopy /S libusb-1.0.21 C:\cygwin\home\appveyor\
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - set CGO_ENABLED=1
  - go version
  - go env
  - go get .\...

build_script:
  - go build -o bin\antgo-$(appveyor_build_worker_image) -i .

artifacts:
  - path: bin\antgo-$(appveyor_build_version)
    name: binary

#deploy:
#  release: antgo-win-$(appveyor_build_version)
#  description: 'Antgo'
#  provider: GitHub
#  auth_token:
#    secure: Aj+IX99Zm3sC+GBkE0eJxMV6k7jubTkpAkBYTgxjZNh5qgsmDAmLHZYadBq0a952
#  artifact: binary # This is the name we specified in the artifacts section.
#  draft: true
#  prerelease: true
#  on:
#    branch: master