platform: x64

clone_folder: c:\gopath\src\github.com\account\myproject

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - set CGO_ENABLED=1
  - go version
  - go env

build_script:
  - SET GOARCH=amd64
  - go build -o bin\antgo-win64 -i .
  - SET GOARCH=386
  - go build -o bin\antgo-win32 -i .

artifacts:
  - path: bin\antgo-win32
  - path: bin\antgo-win64
    name: binary

deploy:
  release: antgo-win-$(appveyor_build_version)
  description: 'Antgo Win'
  provider: GitHub
  auth_token:
    secure: Aj+IX99Zm3sC+GBkE0eJxMV6k7jubTkpAkBYTgxjZNh5qgsmDAmLHZYadBq0a952
  artifact: binary # This is the name we specified in the artifacts section.
  draft: true
  prerelease: true
  on:
    branch: master